---

name: Lint Go Code

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          stable: false
          go-version: 1.16.x
      - name: Lint
        run: |
          URL=https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh
          curl -sSfL "${URL}" | sh -s -- -b $(go env GOPATH)/bin v1.26.0
          golangci-lint run
